apiVersion: v1
kind: Secret
metadata:
  name: redis-cluster
type: Opaque
stringData:
  redis.conf: |
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    requirepass IEPfIr0eLF7UsfwrIlzy80yUaBG258j9
    notify-keyspace-events AKE
